copy "C:\Users\Rob\Documents\Visual Studio 2015\Projects\Utilities\Debug\Utilities.dll" "C:\Users\Rob\Documents\Visual Studio 2015\Projects\AddressKey\Debug"
copy "C:\Users\Rob\Documents\Visual Studio 2015\Projects\DbConnection\Debug\DbConnection.dll" "C:\Users\Rob\Documents\Visual Studio 2015\Projects\AddressKey\Debug"
copy "C:\Users\Rob\Documents\Visual Studio 2015\Projects\DbConnection\Debug\libmysql.dll" "C:\Users\Rob\Documents\Visual Studio 2015\Projects\AddressKey\Debug"
copy "C:\Users\Rob\Documents\Visual Studio 2015\Projects\DbConnection\Debug\mysqlcppconn.dll" "C:\Users\Rob\Documents\Visual Studio 2015\Projects\AddressKey\Debug"
copy "C:\Users\Rob\Documents\Visual Studio 2015\Projects\Metaphone\Debug\Metaphone.dll" "C:\Users\Rob\Documents\Visual Studio 2015\Projects\AddressKey\Debug"
